### ISSUE TITLE
Change the look or design for Response of chatbot 

### ISSUE THREAD

**Issue by Nitin6404** [farish-jamal/GPT-Chatbot#13]
When i visit the chatbot and try to generate some responses i notice one thing whenever the response is generated, the response is in horizontal scroll manner and user only able to see a line at a time which feels weird to use....
What I think if the response is in vertical scroll down manner then it looks good and easy to use 

here is video sample link of the issue 
https://github.com/farish-jamal/GPT-Chatbot/assets/104624489/ee1ac7c2-f5c5-4e4d-804b-a16e0c479dd7

here is image for issue 
![Screenshot 2024-02-13 092947](https://github.com/farish-jamal/GPT-Chatbot/assets/104624489/65bc6bc9-cf39-48fb-a018-3e907487dd19)

**Comment by farish-jamal** [comment]
Thank you for your feedback @Nitin6404 , the issue is now resolved.
